# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [4]:
# number of axes
print(A.ndim)

2


In [5]:
# shape
print(A.shape)

(3, 5)


In [6]:
# size
print(A.size)

15


In [7]:
# datatype
print(A.dtype)

int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [8]:
import numpy as np

B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [9]:
subtraction = B - C
print("\nElementwise subtraction")
print(subtraction)


Elementwise subtraction
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]


In [10]:
multiplication = B * C
print("\nElementwise multiplication")
print(multiplication)



Elementwise multiplication
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [11]:
Matrix_multiplication = B @ C
print("\nMatrix multiplication")
print(Matrix_multiplication)


Matrix multiplication
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


# Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [12]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# Exponentiate each number elementwise (use the np.exp function).
exp = np.exp(B)
print("\nExponentiated Matrix:")
print(exp)


Exponentiated Matrix:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [14]:
# Calculate the minimum value in the whole matrix
min_value = np.min(B)
print("\nThe minimum value")
print(min_value)


The minimum value
1


In [15]:
# Calculcate the minimum value in each row
min_value_row = np.min(B, axis=1)
print("\nminimum value in each row:")
print(min_value_row)


minimum value in each row:
[1 4 7]


In [16]:
# calculate the minimun value in each column
min_value_column = np.min(B, axis=0)
print("\nminimum value in eash column:")
print(min_value_column)


minimum value in eash column:
[1 2 3]


In [17]:
# Find the index value for the minimum value in the whole matrix (hint: use np.argmin)
ind_min = np.argmin(B)
print("\nindex value for the minimum value: ")
print(ind_min)


index value for the minimum value: 
0


In [18]:
# Find the index value for the minimum value in each row (hint: use np.argmin)
ind_min_row = np.argmin(B, axis=0)
print("\nindex value for the minimum value in each row:")
print(ind_min_row)


index value for the minimum value in each row:
[0 0 0]


In [19]:
# Calculate the sum for all elements
sum_el = B.sum()
print("\nthe sum for all elements:")
print(sum_el)


the sum for all elements:
45


In [20]:
# Calculate the mean for each column
mean_clmn = np.mean(B, axis=1)
print("\nthe mean for each column:")
print(mean_clmn)


the mean for each column:
[2. 5. 8.]


In [21]:
# Calculate the median for each column
median_clmn = np.median(B, axis=1)
print("\nthe median for each column:")
print(median_clmn)


the median for each column:
[2. 5. 8.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [22]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [23]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

# When we use A[1], we are specifyingan index for the first dimention, it's equivalent to A[1, :], wich selects the entire second row of the array.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [24]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [25]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [26]:
for row in A:
    for element in row:
        print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [27]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [28]:
a = np.arange(30) # creates a 1D NumPy array a containing integers from 0 to 29 30 (30 elements).
b = a.reshape((2, 3, -1)) # It reshapes this 1D array into a 3D array b.

# b has three axes of dimentions:

# The first axis has a size of 2, which means there are two "slices" along this axis.
# The second axis has a size of 3, which means each slice is further divided into three "rows."
# The third axis : -1 unspecified dimension, the total number of elements remains the same (30). 
# As a result, the 1D array a is reshaped into a 3D array b with dimensions (2, 3, 5).

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [29]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1)
print()
print(m2)
print()
print(m1 + m2)

[[1 2]
 [3 4]]

[1 1]

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [30]:
v1 = np.array([1, 2, 3])
print(v1)
print(v1 + 1)

[1 2 3]
[2 3 4]


In [31]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [32]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])

D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print()
print(B)
print()
print(C)
print()
print(D)
print()
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]

[[ 4 -2  1]
 [ 2 -4 -2]]

[[1 2]
 [2 1]]

[[3 4]
 [4 3]]

[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [33]:
import numpy as np

def add_mult_matrices(m1, m2, operation):
    # Validate that m1 and m2 are numpy.ndarray
    if not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray):
        raise ValueError("Both input matrices must be numpy.ndarray")

    # Validate that the operation is either 'add' or 'multiply'
    if operation not in ('add', 'multiply'):
        raise ValueError("The operation must be 'add' or 'multiply'")

    if operation == 'add':
        # Validate that the matrices have the same shape for addition
        if m1.shape != m2.shape:
            raise ValueError("Matrices must have the same shape for addition")

        # Perform matrix addition
        result = m1 + m2
    else:
        # Validate that the sizes conform for matrix multiplication
        if m1.shape[1] != m2.shape[0]:
            raise ValueError("Matrix sizes do not conform for multiplication")

        # Perform matrix multiplication
        result = np.dot(m1, m2)

    return result


In [34]:

# Example usage:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
matrices_addition = add_mult_matrices(m1, m2, 'add')
matrices_multiplication = add_mult_matrices(m1, m2, 'multiply')

print("Matrix Addition:")
print(matrices_addition)
print("\nMatrix Multiplication:")
print(matrices_multiplication)

Matrix Addition:
[[ 6  8]
 [10 12]]

Matrix Multiplication:
[[19 22]
 [43 50]]


**Chap2. Question 2**

In [35]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])



In [39]:
AB = add_mult_matrices(A, B, 'multiply')
AC = add_mult_matrices(A, C, 'multiply')

print('AB:', '\n', AB)
print('AC:', '\n', AC)

# AB = AC and yet B is not equal to C.

AB: 
 [[ 4  7]
 [ 8 14]]
AC: 
 [[ 4  7]
 [ 8 14]]


**Chap2. Question 3**

In [ ]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

In [42]:
print('AD:', '\n', add_mult_matrices(A, D, 'multiply'))
print('DA:', '\n', add_mult_matrices(D, A, 'multiply'))

AD: 
 [[11 10]
 [22 20]]
DA: 
 [[11 22]
 [10 20]]


**Chap 6. Question 1**

In [45]:
M1 = np.array([[5, 6], [4, 5]])
M2 = np.array([[6, 4], [3, 3]])

In [46]:
# Calculate the inverses using np.linalg.inv
M1_inverse = np.linalg.inv(M1)
M2_inverse = np.linalg.inv(M2)

In [54]:
print("Inverse of M1:\n", M1_inverse, "\nInverse of M2:\n", M2_inverse)

Inverse of M1:
 [[ 5. -6.]
 [-4.  5.]] 
Inverse of M2:
 [[ 0.5        -0.66666667]
 [-0.5         1.        ]]


In [57]:
# Check if M1 @ M1_inv is the identity matrix (using np.allclose)
print(np.allclose(np.dot(M1, M1_inv), np.eye(2)))

True


**Chap10. Question 1 a)**

In [58]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
B = np.array([-7, 5, 2])

In [61]:
print(A)
print(B)

[[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]
[-7  5  2]


In [63]:
# The system solution
x = np.linalg.solve(A, B)
print(x)

[ 3.  4. -6.]


**Chap10. Question 1 b)**

In [64]:
C = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
D = np.array([1, -1, 1])

In [67]:
print(C)
print(D)

[[ 1 -2  3]
 [-1  3 -1]
 [ 2 -5  5]]
[ 1 -1  1]


In [65]:
# The system solution
x = np.linalg.solve(C, D)
print(x)

[ 8.  2. -1.]


**Chap 12. Question 1**

In [69]:
M = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
print(M)

[[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]


In [70]:
M_inv = np.linalg.inv(M)
print(M_inv)
# Check if M1 @ M1_inv is the identity matrix
print(np.allclose(M @ M_inv, np.eye(3)))

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]
True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [56]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [57]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [34]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
